### PR TITLE
Fixes issue #91

### PR DESCRIPTION
**Pull request by markwatsonatx**

### CODE REVIEW

**Comment by willholley** [comment]
@markwatsonatx can you update the commit message so it includes the reason for the change? It's useful to reference a GH issue in the commit but shouldn't be a requirement to understand the change.

**Comment by markwatsonatx** [comment]
Well, I used git commit --amend and got into some merge scenario, so there are a couple of extra commit messages in there. Is this good, or is there something else I should do? I see the PR name didn't change.

**Comment by willholley** [comment]
eek - looks like something odd happened there. You could `git rebase -i HEAD~6`, remove the spurious commits and reword the one you want keep.

**Comment by markwatsonatx** [comment]
I ended up having to do a reset as rebase -i didn't list those commits. Originally when I did a git commit --amend I didn't force the push to the remote origin - that was the issue. I did that this time and it seems to have worked.

**Comment by willholley** [comment]
perfect - thanks!

**Pull request merged**
