### PR TITLE
refactor auth and access to support custom plugins

### PR DESCRIPTION
**Pull request by Xiphe**
custom plugins might also need the app and a router so these are passed into a plugin factory.

refactor internal plugins to factory style.

I have not used `app` and `router` in existing plugins, in order to not blow up the changeset.

### CODE REVIEW

**Comment by Xiphe** [comment]
Local test have not worked for me, optimistically waiting for travis 😄

**Comment by Xiphe** [comment]
PTAL @glynnbird

**Comment by pickettd** [comment]
I believe the internal meta plugin is not working now. I tried to use the plugin to get a single doc and got the error that app is not defined (as the meta plugin uses app.metaKey).

**Comment by glynnbird** [comment]
@pickettd would you mind submitting a PR to fix (on a new branch)?

**Comment by pickettd** [comment]
@glynnbird sure - I submitted https://github.com/cloudant-labs/envoy/pull/176

**Comment by Xiphe** [comment]
Oh, sorry that slipped through.

**Pull request merged**
